/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 14/05/2012, 02:06:43
 */
package GUI;

/**
 *
 * @author pc
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        this.jButton1.setText("<html><center> <p><font face='Courier New' size='5'> Registrar Atividade </font></p></center> </html>");
        this.jButton2.setText("<html><center> <p><font face='Courier New' size='5'> Visualizar Desgaste de Peça </font></p></center> </html>");
        this.jButton3.setText("<html><center> <p><font face='Courier New' size='5'> Relatório de Peça </font></p></center> </html>");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSemeadora = new javax.swing.JMenu();
        menuItemRegSemeadora = new javax.swing.JMenuItem();
        menuItemConsSemeadora = new javax.swing.JMenuItem();
        menuItemEditSemeadora = new javax.swing.JMenuItem();
        menuItemExcSemeadora = new javax.swing.JMenuItem();
        menuPeca = new javax.swing.JMenu();
        menuItemRegPeca = new javax.swing.JMenuItem();
        menuItemConsPeca = new javax.swing.JMenuItem();
        menuItemEditPeca = new javax.swing.JMenuItem();
        menuItemExcPeca = new javax.swing.JMenuItem();
        menuItemVisDesgPeca = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuAtividade = new javax.swing.JMenu();
        menuManutencao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MPS - Manutenção Preditiva de Semeadoras");
        setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 14));
        jButton1.setText("Registrar Atividade");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/question_mark.gif"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        menuSemeadora.setText("Semeadora");

        menuItemRegSemeadora.setText("Registrar Semeadora");
        menuSemeadora.add(menuItemRegSemeadora);

        menuItemConsSemeadora.setText("Consultar Semeadora");
        menuSemeadora.add(menuItemConsSemeadora);

        menuItemEditSemeadora.setText("Editar Semeadora");
        menuSemeadora.add(menuItemEditSemeadora);

        menuItemExcSemeadora.setText("Excluir Semeadora");
        menuSemeadora.add(menuItemExcSemeadora);

        jMenuBar1.add(menuSemeadora);

        menuPeca.setText("Peça");

        menuItemRegPeca.setText("Registrar Peça");
        menuPeca.add(menuItemRegPeca);

        menuItemConsPeca.setText("Consultar Peça");
        menuItemConsPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsPecaActionPerformed(evt);
            }
        });
        menuPeca.add(menuItemConsPeca);

        menuItemEditPeca.setText("Editar Peça");
        menuPeca.add(menuItemEditPeca);

        menuItemExcPeca.setText("Excluir Peça");
        menuItemExcPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExcPecaActionPerformed(evt);
            }
        });
        menuPeca.add(menuItemExcPeca);

        menuItemVisDesgPeca.setText("Visualizar Desgaste de Peça");
        menuPeca.add(menuItemVisDesgPeca);

        jMenuItem2.setText("Relatório de Peça");
        menuPeca.add(jMenuItem2);

        jMenuBar1.add(menuPeca);

        menuAtividade.setText("Atividade");
        jMenuBar1.add(menuAtividade);

        menuManutencao.setText("Manutenção");
        jMenuBar1.add(menuManutencao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jRadioButton2)))
                        .addGap(50, 50, 50)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menuItemConsPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsPecaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menuItemConsPecaActionPerformed


private void menuItemExcPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExcPecaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menuItemExcPecaActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JMenu menuAtividade;
    private javax.swing.JMenuItem menuItemConsPeca;
    private javax.swing.JMenuItem menuItemConsSemeadora;
    private javax.swing.JMenuItem menuItemEditPeca;
    private javax.swing.JMenuItem menuItemEditSemeadora;
    private javax.swing.JMenuItem menuItemExcPeca;
    private javax.swing.JMenuItem menuItemExcSemeadora;
    private javax.swing.JMenuItem menuItemRegPeca;
    private javax.swing.JMenuItem menuItemRegSemeadora;
    private javax.swing.JMenuItem menuItemVisDesgPeca;
    private javax.swing.JMenu menuManutencao;
    private javax.swing.JMenu menuPeca;
    private javax.swing.JMenu menuSemeadora;
    // End of variables declaration//GEN-END:variables
}
