/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author rafael
 */
public class TelaCartas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    ImageIcon imgCarta = new ImageIcon("large_clipart_quenclub_nifterdotcom.gif");
    
    public TelaCartas() {
        initComponents();
        
        lbCtCarta1.setIcon(imgCarta);
        lbCtCarta2.setIcon(imgCarta);
        lbCtCarta3.setIcon(imgCarta);
        
        lbMaoCarta1.setIcon(imgCarta);
        lbMaoCarta2.setIcon(imgCarta);
        lbMaoCarta3.setIcon(imgCarta);
        
        
    }
    
    public ImageIcon ajustarImagem(ComponentEvent evt, ImageIcon imagem, JComponent lbImagem){
        
        return new ImageIcon(imagem.getImage().getScaledInstance(lbImagem.getWidth(), lbImagem.getHeight(), Image.SCALE_DEFAULT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCtCartas = new javax.swing.JPanel();
        pnCtCarta1 = new javax.swing.JPanel();
        lbCtCarta1 = new javax.swing.JLabel();
        pnCtCarta2 = new javax.swing.JPanel();
        lbCtCarta2 = new javax.swing.JLabel();
        pnCtCarta3 = new javax.swing.JPanel();
        lbCtCarta3 = new javax.swing.JLabel();
        pnConfronto = new javax.swing.JPanel();
        pnCftCarta1 = new javax.swing.JPanel();
        lbCftCarta1 = new javax.swing.JLabel();
        lbCft = new javax.swing.JLabel();
        pnCft2 = new javax.swing.JPanel();
        lbCftCarta2 = new javax.swing.JLabel();
        pnMaoCartas = new javax.swing.JPanel();
        pnMaoCarta1 = new javax.swing.JPanel();
        lbMaoCarta1 = new javax.swing.JLabel();
        pnMaoCarta2 = new javax.swing.JPanel();
        lbMaoCarta2 = new javax.swing.JLabel();
        pnMaocarta3 = new javax.swing.JPanel();
        lbMaoCarta3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1, 0, 20));

        pnCtCartas.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        pnCtCarta1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnCtCarta1ComponentResized(evt);
            }
        });
        pnCtCarta1.setLayout(new java.awt.BorderLayout());

        lbCtCarta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCtCarta1MouseClicked(evt);
            }
        });
        pnCtCarta1.add(lbCtCarta1, java.awt.BorderLayout.CENTER);

        pnCtCartas.add(pnCtCarta1);

        pnCtCarta2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnCtCarta2ComponentResized(evt);
            }
        });
        pnCtCarta2.setLayout(new java.awt.BorderLayout());

        lbCtCarta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCtCarta2MouseClicked(evt);
            }
        });
        pnCtCarta2.add(lbCtCarta2, java.awt.BorderLayout.CENTER);

        pnCtCartas.add(pnCtCarta2);

        pnCtCarta3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnCtCarta3ComponentResized(evt);
            }
        });
        pnCtCarta3.setLayout(new java.awt.BorderLayout());

        lbCtCarta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCtCarta3MouseClicked(evt);
            }
        });
        pnCtCarta3.add(lbCtCarta3, java.awt.BorderLayout.CENTER);

        pnCtCartas.add(pnCtCarta3);

        getContentPane().add(pnCtCartas);

        pnConfronto.setLayout(new java.awt.GridLayout(1, 3));

        pnCftCarta1.setLayout(new java.awt.BorderLayout());

        lbCftCarta1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lbCftCarta1ComponentResized(evt);
            }
        });
        pnCftCarta1.add(lbCftCarta1, java.awt.BorderLayout.CENTER);

        pnConfronto.add(pnCftCarta1);

        lbCft.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbCft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCft.setText("X");
        pnConfronto.add(lbCft);

        pnCft2.setLayout(new java.awt.BorderLayout());

        lbCftCarta2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lbCftCarta2ComponentResized(evt);
            }
        });
        pnCft2.add(lbCftCarta2, java.awt.BorderLayout.CENTER);

        pnConfronto.add(pnCft2);

        getContentPane().add(pnConfronto);

        pnMaoCartas.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        pnMaoCarta1.setLayout(new java.awt.BorderLayout());

        lbMaoCarta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMaoCarta1MouseClicked(evt);
            }
        });
        lbMaoCarta1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lbMaoCarta1ComponentResized(evt);
            }
        });
        pnMaoCarta1.add(lbMaoCarta1, java.awt.BorderLayout.CENTER);

        pnMaoCartas.add(pnMaoCarta1);

        pnMaoCarta2.setLayout(new java.awt.BorderLayout());

        lbMaoCarta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMaoCarta2MouseClicked(evt);
            }
        });
        lbMaoCarta2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lbMaoCarta2ComponentResized(evt);
            }
        });
        pnMaoCarta2.add(lbMaoCarta2, java.awt.BorderLayout.CENTER);

        pnMaoCartas.add(pnMaoCarta2);

        pnMaocarta3.setLayout(new java.awt.BorderLayout());

        lbMaoCarta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMaoCarta3MouseClicked(evt);
            }
        });
        lbMaoCarta3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lbMaoCarta3ComponentResized(evt);
            }
        });
        pnMaocarta3.add(lbMaoCarta3, java.awt.BorderLayout.CENTER);

        pnMaoCartas.add(pnMaocarta3);

        getContentPane().add(pnMaoCartas);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnCtCarta1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnCtCarta1ComponentResized
        if(lbCtCarta1.getIcon() != null)
            lbCtCarta1.setIcon(ajustarImagem(evt, imgCarta, lbCtCarta1));
    }//GEN-LAST:event_pnCtCarta1ComponentResized

    private void pnCtCarta2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnCtCarta2ComponentResized
        if(lbCtCarta2.getIcon() != null)
            lbCtCarta2.setIcon(ajustarImagem(evt, imgCarta, lbCtCarta2));
    }//GEN-LAST:event_pnCtCarta2ComponentResized

    private void pnCtCarta3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnCtCarta3ComponentResized
        if(lbCtCarta3.getIcon() != null)
            lbCtCarta3.setIcon(ajustarImagem(evt, imgCarta, lbCtCarta3));
    }//GEN-LAST:event_pnCtCarta3ComponentResized

    private void lbCftCarta1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbCftCarta1ComponentResized
        
        if(lbCftCarta1.getIcon() != null)
            lbCftCarta1.setIcon(ajustarImagem(evt, imgCarta, lbCftCarta1));
    }//GEN-LAST:event_lbCftCarta1ComponentResized

    private void lbCftCarta2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbCftCarta2ComponentResized
        
        if(lbCftCarta2.getIcon() != null)
            lbCftCarta2.setIcon(ajustarImagem(evt, imgCarta, lbCftCarta2));
    }//GEN-LAST:event_lbCftCarta2ComponentResized

    private void lbMaoCarta1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbMaoCarta1ComponentResized
        
        if(lbMaoCarta1.getIcon() != null)
            lbMaoCarta1.setIcon(ajustarImagem(evt, imgCarta, lbMaoCarta1));
    }//GEN-LAST:event_lbMaoCarta1ComponentResized

    private void lbMaoCarta2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbMaoCarta2ComponentResized
        
        if(lbMaoCarta2.getIcon() != null)
            lbMaoCarta2.setIcon(ajustarImagem(evt, imgCarta, lbMaoCarta2));
    }//GEN-LAST:event_lbMaoCarta2ComponentResized

    private void lbMaoCarta3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbMaoCarta3ComponentResized
        
        if(lbMaoCarta3.getIcon() != null)
            lbMaoCarta3.setIcon(ajustarImagem(evt, imgCarta, lbMaoCarta3));
    }//GEN-LAST:event_lbMaoCarta3ComponentResized

    private void lbCtCarta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCtCarta1MouseClicked
        
        if(lbCftCarta1.getIcon() == null && lbCtCarta1.getIcon() != null){
            
            lbCftCarta1.setIcon(ajustarImagem(evt, (ImageIcon)lbCtCarta1.getIcon(), lbCftCarta1));
            lbCftCarta1.setIcon(null);
        }else if(lbCftCarta2.getIcon() == null && lbCtCarta1.getIcon() != null){
            
            lbCftCarta2.setIcon(ajustarImagem(evt, (ImageIcon)lbCtCarta1.getIcon(), lbCftCarta2));
            lbCtCarta1.setIcon(null);
        }
    }//GEN-LAST:event_lbCtCarta1MouseClicked

    private void lbCtCarta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCtCarta2MouseClicked
        
        if(lbCftCarta1.getIcon() == null && lbCtCarta2.getIcon() != null){
            
            lbCftCarta1.setIcon(ajustarImagem(evt, (ImageIcon)lbCtCarta2.getIcon(), lbCftCarta1));
            lbCftCarta1.setIcon(null);
        }else if(lbCftCarta2.getIcon() == null && lbCtCarta2.getIcon() != null){
            
            lbCftCarta2.setIcon(ajustarImagem(evt, (ImageIcon)lbCtCarta2.getIcon(), lbCftCarta2));
            lbCtCarta2.setIcon(null);
        }
    }//GEN-LAST:event_lbCtCarta2MouseClicked

    private void lbCtCarta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCtCarta3MouseClicked
        
        if(lbCftCarta1.getIcon() == null && lbCtCarta3.getIcon() != null){
            
            lbCftCarta1.setIcon(ajustarImagem(evt, (ImageIcon)lbCtCarta3.getIcon(), lbCftCarta1));
            lbCftCarta1.setIcon(null);
        }else if(lbCftCarta2.getIcon() == null && lbCtCarta3.getIcon() != null){
            
            lbCftCarta2.setIcon(ajustarImagem(evt, (ImageIcon)lbCtCarta3.getIcon(), lbCftCarta2));
            lbCtCarta3.setIcon(null);
        }
    }//GEN-LAST:event_lbCtCarta3MouseClicked

    private void lbMaoCarta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMaoCarta1MouseClicked
        
        if(lbCftCarta1.getIcon() == null && lbMaoCarta1.getIcon() != null){
            
            lbCftCarta1.setIcon(ajustarImagem(evt, (ImageIcon)lbMaoCarta1.getIcon(), lbCftCarta1));
            lbMaoCarta1.setIcon(null);
        }else if(lbCftCarta2.getIcon() == null && lbMaoCarta1.getIcon() != null){
            
            lbCftCarta2.setIcon(ajustarImagem(evt, (ImageIcon)lbMaoCarta1.getIcon(), lbCftCarta2));
            lbMaoCarta1.setIcon(null);
        }
    }//GEN-LAST:event_lbMaoCarta1MouseClicked

    private void lbMaoCarta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMaoCarta2MouseClicked
        
        if(lbCftCarta1.getIcon() == null && lbMaoCarta2.getIcon() != null){
            
            lbCftCarta1.setIcon(ajustarImagem(evt, (ImageIcon)lbMaoCarta2.getIcon(), lbCftCarta1));
            lbMaoCarta2.setIcon(null);
        }else if(lbCftCarta2.getIcon() == null && lbMaoCarta1.getIcon() != null){
            
            lbCftCarta2.setIcon(ajustarImagem(evt, (ImageIcon)lbMaoCarta1.getIcon(), lbCftCarta2));
            lbMaoCarta1.setIcon(null);
        }
    }//GEN-LAST:event_lbMaoCarta2MouseClicked

    private void lbMaoCarta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMaoCarta3MouseClicked
        
        if(lbCftCarta1.getIcon() == null && lbMaoCarta3.getIcon() != null){
            
            lbCftCarta1.setIcon(ajustarImagem(evt, (ImageIcon)lbMaoCarta3.getIcon(), lbCftCarta1));
            lbMaoCarta3.setIcon(null);
        }else if(lbCftCarta2.getIcon() == null && lbMaoCarta3.getIcon() != null){
            
            lbCftCarta2.setIcon(ajustarImagem(evt, (ImageIcon)lbMaoCarta3.getIcon(), lbCftCarta2));
            lbMaoCarta3.setIcon(null);
        }
    }//GEN-LAST:event_lbMaoCarta3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCartas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCft;
    private javax.swing.JLabel lbCftCarta1;
    private javax.swing.JLabel lbCftCarta2;
    private javax.swing.JLabel lbCtCarta1;
    private javax.swing.JLabel lbCtCarta2;
    private javax.swing.JLabel lbCtCarta3;
    private javax.swing.JLabel lbMaoCarta1;
    private javax.swing.JLabel lbMaoCarta2;
    private javax.swing.JLabel lbMaoCarta3;
    private javax.swing.JPanel pnCft2;
    private javax.swing.JPanel pnCftCarta1;
    private javax.swing.JPanel pnConfronto;
    private javax.swing.JPanel pnCtCarta1;
    private javax.swing.JPanel pnCtCarta2;
    private javax.swing.JPanel pnCtCarta3;
    private javax.swing.JPanel pnCtCartas;
    private javax.swing.JPanel pnMaoCarta1;
    private javax.swing.JPanel pnMaoCarta2;
    private javax.swing.JPanel pnMaoCartas;
    private javax.swing.JPanel pnMaocarta3;
    // End of variables declaration//GEN-END:variables
}
